global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: '*******@gmail.com'
        from: '*******@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: '*******@gmail.com'
        auth_identity: '***********'